name: automacao_residencial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  flutter_launcher_icons: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true


# Adicione esta seção inteira no final do arquivo
flutter_launcher_icons:
  # Configurações para Android
  android: "launcher_icon"
  # Configurações para iOS
  ios: true
  # Caminho para a sua imagem de ícone
  image_path: "assets/icon/icon.png"